<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MapDataManager</AssemblyName>
    <RootNamespace>MapDataManager</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mapsui" Version="5.0.0" />
    <PackageReference Include="Mapsui.Wpf" Version="5.0.0" />
    <PackageReference Include="BruTile" Version="5.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.8" />
  </ItemGroup>
</Project>
