import React, { useEffect, useRef, useState } from 'react';
import * as L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { FolderOpen, RefreshCw, Server, MapPinned } from 'lucide-react';

interface ScanResult { files:number; tiles:number; zooms:number[]; root:string|null; bounds:{minLat:number;minLng:number;maxLat:number;maxLng:number}|null; }

export default function OfflineRasterMap(){
 const mapEl=useRef<HTMLDivElement>(null); const mapRef=useRef<L.Map|null>(null); const layerRef=useRef<L.TileLayer|null>(null);
 const [folder,setFolder]=useState(''); const [scan,setScan]=useState<ScanResult|null>(null); const [server,setServer]=useState(''); const [scheme,setScheme]=useState<'xyz'|'tms'>('xyz'); const [status,setStatus]=useState('Select an offline map folder'); const [error,setError]=useState('');
 const scanFolder=async()=>{ if(!window.electronAPI){setError('Run the Electron desktop application.');return;} setError(''); setStatus('Scanning map folder...'); try{const r=await window.electronAPI.scanOfflineFolder();setScan(r);setStatus(r.tiles?`${r.tiles.toLocaleString()} tiles ready`:'No raster tiles found');}catch(e){setError(e instanceof Error?e.message:String(e));setStatus('Scan failed');} };
 useEffect(()=>{if(!mapEl.current||mapRef.current)return;const m=L.map(mapEl.current,{zoomControl:true,preferCanvas:false});m.setView([30.3753,69.3451],5);L.control.scale({imperial:false}).addTo(m);mapRef.current=m;window.electronAPI?.getTileServerUrl().then(setServer).catch(()=>{});return()=>{m.remove();mapRef.current=null;};},[]);
 useEffect(()=>{if(!mapRef.current||!server||!scan?.tiles||!scan.zooms.length)return;if(layerRef.current)layerRef.current.remove();const layer=L.tileLayer(`${server}/tiles/{z}/{x}/{y}.png`,{minZoom:Math.min(...scan.zooms),maxZoom:Math.max(...scan.zooms),tileSize:256,noWrap:true,keepBuffer:2,tms:scheme==='tms',attribution:'Offline raster map'});layer.addTo(mapRef.current);layerRef.current=layer;if(scan.bounds){const b=L.latLngBounds([scan.bounds.minLat,scan.bounds.minLng],[scan.bounds.maxLat,scan.bounds.maxLng]);if(b.isValid())mapRef.current.fitBounds(b,{padding:[30,30],maxZoom:Math.max(...scan.zooms)});}setStatus(`${scan.tiles.toLocaleString()} tiles loaded • Zoom ${scan.zooms.join(', ')}`);},[scan,server,scheme]);
 const selectFolder=async()=>{if(!window.electronAPI){setError('Run the Electron desktop application, not the browser preview.');return;}setError('');const s=await window.electronAPI.selectOfflineFolder();if(!s)return;setFolder(s.path);setServer(s.tileUrl.replace('/tiles/{z}/{x}/{y}.png',''));setTimeout(scanFolder,100);};
 return <div className="w-full h-full min-h-0 bg-slate-200 rounded-xl overflow-hidden border border-slate-300 shadow-inner relative flex flex-col">
  <div className="absolute top-3 left-3 right-3 z-[1000] flex flex-wrap gap-2 pointer-events-none"><div className="bg-white/95 rounded-lg border border-slate-200 shadow-lg px-3 py-2 pointer-events-auto"><div className="flex items-center gap-2"><MapPinned className="w-4 h-4 text-green-600"/><span className="text-xs font-bold uppercase tracking-wider">Offline Map View</span><button onClick={selectFolder} className="ml-2 flex items-center gap-1.5 bg-green-600 hover:bg-green-700 text-white text-xs font-semibold px-3 py-1.5 rounded-md"><FolderOpen className="w-3.5 h-3.5"/>Select Map Folder</button><button onClick={scanFolder} disabled={!folder} className="flex items-center gap-1.5 bg-slate-100 disabled:opacity-40 text-slate-700 text-xs font-semibold px-3 py-1.5 rounded-md"><RefreshCw className="w-3.5 h-3.5"/>Rescan</button><select value={scheme} onChange={e=>setScheme(e.target.value as 'xyz'|'tms')} className="text-xs border rounded-md px-2 py-1.5 bg-white"><option value="xyz">XYZ</option><option value="tms">TMS</option></select></div>{folder&&<div className="mt-1 text-[10px] text-slate-500 max-w-[680px] truncate" title={folder}>{folder}</div>}</div><div className="bg-white/95 rounded-lg border border-slate-200 shadow-lg px-3 py-2 text-[10px] text-slate-600 pointer-events-auto"><div className="flex items-center gap-1.5"><Server className="w-3 h-3"/>Local tile server {server?'READY':'STARTING'}</div><div className="font-semibold text-green-700 mt-0.5">{status}</div>{scan?.bounds&&<div>Coverage {scan.bounds.minLat.toFixed(3)}, {scan.bounds.minLng.toFixed(3)} → {scan.bounds.maxLat.toFixed(3)}, {scan.bounds.maxLng.toFixed(3)}</div>}</div></div>
  {error&&<div className="absolute top-24 left-3 right-3 z-[1001] bg-red-50 border border-red-300 text-red-700 rounded-lg px-3 py-2 text-xs shadow-lg">{error}</div>}<div ref={mapEl} className="flex-1 w-full min-h-0"/>
 </div>;
}
