import React, { useEffect, useRef, useState } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { Download, FolderOpen, MapPinned, Mountain, Navigation, Search, Satellite } from 'lucide-react';
import { formatCoordinate, parseCoordinateText, type Coordinate } from '../map/coordinates';
import { searchOffline, searchOnline, type MapSearchResult } from '../map/searchService';

interface ScanResult { files:number; tiles:number; zooms:number[]; root:string|null; bounds:{minLat:number;minLng:number;maxLat:number;maxLng:number}|null; }
interface DownloadProgress { done:number; total:number; downloaded:number; }
interface ElectronAPI { selectOfflineFolder:()=>Promise<{path:string;tileUrl:string}|null>; selectSatelliteFolder:()=>Promise<{path:string;tileUrl:string}|null>; selectTerrainFolder:()=>Promise<{path:string;tileUrl:string}|null>; selectDownloadDestination:()=>Promise<string|null>; scanOfflineFolder:()=>Promise<ScanResult>; scanSatelliteFolder:()=>Promise<ScanResult>; scanTerrainFolder:()=>Promise<ScanResult>; getTileServerUrl:()=>Promise<string>; downloadTiles:(options:unknown)=>Promise<{done:number;total:number;downloaded:number;destination:string}>; onDownloadProgress:(callback:(progress:DownloadProgress)=>void)=>void; }
declare global { interface Window { electronAPI?: ElectronAPI } }
type Mode='online'|'offline'; type BaseLayer='streets'|'satellite'; type TerrainLayer='none'|'terrain'; type ToolTab='map'|'search'|'coordinates'|'offline'|'download';
const PAKISTAN={minLat:23.5,maxLat:37.1,minLng:60.8,maxLng:77.1};
const ONLINE_STREETS='https://tile.openstreetmap.org/{z}/{x}/{y}.png'; const ONLINE_SATELLITE='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'; const ONLINE_TERRAIN='https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png';

export default function Phase1Map(){
 const mapEl=useRef<HTMLDivElement>(null),mapRef=useRef<L.Map|null>(null),baseRef=useRef<L.TileLayer|null>(null),terrainRef=useRef<L.TileLayer|null>(null),markerRef=useRef<L.CircleMarker|null>(null),highlightRef=useRef<L.Circle|null>(null);
 const [tool,setTool]=useState<ToolTab>('map'),[mode,setMode]=useState<Mode>('offline'),[baseLayer,setBaseLayer]=useState<BaseLayer>('streets'),[terrainLayer,setTerrainLayer]=useState<TerrainLayer>('none');
 const [scan,setScan]=useState<ScanResult|null>(null),[satScan,setSatScan]=useState<ScanResult|null>(null),[terrainScan,setTerrainScan]=useState<ScanResult|null>(null),[server,setServer]=useState(''),[scheme,setScheme]=useState<'xyz'|'tms'>('xyz');
 const [query,setQuery]=useState(''),[searchMode,setSearchMode]=useState<Mode>('offline'),[results,setResults]=useState<MapSearchResult[]>([]),[searching,setSearching]=useState(false),[coordinateText,setCoordinateText]=useState('30.375300, 69.345100'),[mouseCoordinate,setMouseCoordinate]=useState<Coordinate|null>(null),[selected,setSelected]=useState<MapSearchResult|null>(null);
 const [downloadZoom,setDownloadZoom]=useState(1),[downloadMaxZoom,setDownloadMaxZoom]=useState(8),[downloadArea,setDownloadArea]=useState<'view'|'pakistan'>('view'),[downloadSource,setDownloadSource]=useState<'streets'|'satellite'|'terrain'>('satellite'),[progress,setProgress]=useState<DownloadProgress|null>(null),[downloading,setDownloading]=useState(false),[zoom,setZoom]=useState(5),[status,setStatus]=useState('Ready'),[error,setError]=useState('');
 useEffect(()=>{if(!mapEl.current||mapRef.current)return;const map=L.map(mapEl.current,{zoomControl:false,minZoom:0,maxZoom:19,preferCanvas:true,worldCopyJump:false,zoomAnimation:false,fadeAnimation:false,markerZoomAnimation:false,updateWhenIdle:true,keepBuffer:2}).setView([30.3753,69.3451],5);L.control.scale({imperial:false}).addTo(map);map.on('zoomend',()=>setZoom(map.getZoom()));map.on('mousemove',(e:L.LeafletMouseEvent)=>setMouseCoordinate({lat:e.latlng.lat,lon:e.latlng.lng}));map.on('mouseout',()=>setMouseCoordinate(null));mapRef.current=map;window.electronAPI?.getTileServerUrl().then(setServer).catch(()=>{});window.electronAPI?.onDownloadProgress(setProgress);return()=>{map.remove();mapRef.current=null;};},[]);
 useEffect(()=>{const map=mapRef.current;if(!map)return;if(baseRef.current){map.removeLayer(baseRef.current);baseRef.current=null;}if(mode==='online'){baseRef.current=L.tileLayer(baseLayer==='satellite'?ONLINE_SATELLITE:ONLINE_STREETS,{minZoom:0,maxZoom:19,maxNativeZoom:19,keepBuffer:2,updateWhenIdle:true,attribution:baseLayer==='satellite'?'Tiles © Esri':'© OpenStreetMap contributors'}).addTo(map);setStatus(`Online ${baseLayer==='satellite'?'satellite':'street'} map ready`);return;}const s=baseLayer==='satellite'?satScan:scan;if(!server||!s?.tiles||!s.zooms.length){setStatus('Select offline map data');return;}const lo=Math.min(...s.zooms),hi=Math.max(...s.zooms),ep=baseLayer==='satellite'?'satellite':'tiles';baseRef.current=L.tileLayer(`${server}/${ep}/{z}/{x}/{y}.png`,{minZoom:lo,maxZoom:hi,maxNativeZoom:hi,tileSize:256,noWrap:true,keepBuffer:2,updateWhenIdle:true,tms:scheme==='tms',attribution:'Offline map data'}).addTo(map);setStatus(`${s.tiles.toLocaleString()} tiles • Zoom ${lo}–${hi}`);if(s.bounds){const b=L.latLngBounds([s.bounds.minLat,s.bounds.minLng],[s.bounds.maxLat,s.bounds.maxLng]);if(b.isValid())map.fitBounds(b,{padding:[30,30],maxZoom:hi});}},[mode,baseLayer,server,scan,satScan,scheme]);
 useEffect(()=>{const map=mapRef.current;if(!map)return;if(terrainRef.current){map.removeLayer(terrainRef.current);terrainRef.current=null;}if(terrainLayer==='none')return;if(mode==='online'){terrainRef.current=L.tileLayer(ONLINE_TERRAIN,{minZoom:0,maxZoom:17,maxNativeZoom:17,opacity:.48,keepBuffer:2,updateWhenIdle:true,attribution:'© OpenTopoMap contributors'}).addTo(map);return;}if(!server||!terrainScan?.tiles||!terrainScan.zooms.length){setStatus('Select offline terrain data');return;}const lo=Math.min(...terrainScan.zooms),hi=Math.max(...terrainScan.zooms);terrainRef.current=L.tileLayer(`${server}/terrain/{z}/{x}/{y}.png`,{minZoom:lo,maxZoom:hi,maxNativeZoom:hi,opacity:.48,tileSize:256,noWrap:true,keepBuffer:2,updateWhenIdle:true,tms:scheme==='tms',attribution:'Offline terrain'}).addTo(map);},[mode,terrainLayer,server,terrainScan,scheme]);
 const selectBase=async()=>{try{if(!window.electronAPI)throw Error('Run the Electron desktop application.');const s=await window.electronAPI.selectOfflineFolder();if(!s)return;setMode('offline');setBaseLayer('streets');setScan(await window.electronAPI.scanOfflineFolder());setTool('offline');}catch(e){setError(e instanceof Error?e.message:String(e));}};
 const selectSat=async()=>{try{if(!window.electronAPI)throw Error('Run the Electron desktop application.');const s=await window.electronAPI.selectSatelliteFolder();if(!s)return;setMode('offline');setBaseLayer('satellite');setSatScan(await window.electronAPI.scanSatelliteFolder());setTool('offline');}catch(e){setError(e instanceof Error?e.message:String(e));}};
 const selectTerrain=async()=>{try{if(!window.electronAPI)throw Error('Run the Electron desktop application.');const s=await window.electronAPI.selectTerrainFolder();if(!s)return;setMode('offline');setTerrainScan(await window.electronAPI.scanTerrainFolder());setTerrainLayer('terrain');setTool('offline');}catch(e){setError(e instanceof Error?e.message:String(e));}};
 const clear=()=>{const m=mapRef.current;if(m&&markerRef.current)m.removeLayer(markerRef.current);if(m&&highlightRef.current)m.removeLayer(highlightRef.current);markerRef.current=null;highlightRef.current=null;setSelected(null);};
 const showResult=(r:MapSearchResult)=>{const m=mapRef.current;if(!m)return;clear();const ll=L.latLng(r.lat,r.lon);m.setView(ll,Math.max(m.getZoom(),10),{animate:true});markerRef.current=L.circleMarker(ll,{radius:9,color:'#fff',weight:3,fillColor:'#dc2626',fillOpacity:1}).addTo(m);markerRef.current.bindTooltip(r.name,{permanent:true,direction:'top',offset:[0,-10]}).openTooltip();highlightRef.current=L.circle(ll,{radius:1800,color:'#ef4444',weight:2,fillColor:'#fca5a5',fillOpacity:.18,interactive:false}).addTo(m);setSelected(r);setCoordinateText(formatCoordinate({lat:r.lat,lon:r.lon}));};
 const search=async()=>{if(!query.trim())return;setError('');setSearching(true);try{const found=searchMode==='offline'?searchOffline(query):await searchOnline(query);setResults(found);if(found[0])showResult(found[0]);else setError('No matching place found.');}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setSearching(false);}};
 const goto=()=>{const c=parseCoordinateText(coordinateText),m=mapRef.current;if(!c||!m){setError('Use latitude, longitude');return;}clear();m.setView([c.lat,c.lon],Math.max(m.getZoom(),12),{animate:true});markerRef.current=L.circleMarker([c.lat,c.lon],{radius:8,color:'#fff',weight:3,fillColor:'#2563eb',fillOpacity:1}).addTo(m);markerRef.current.bindTooltip('Go-to coordinate',{permanent:true,direction:'top'}).openTooltip();};
 const download=async()=>{const m=mapRef.current;if(!m||!window.electronAPI)return;if(downloadZoom>downloadMaxZoom){setError('Minimum zoom cannot be greater than maximum zoom.');return;}const destination=await window.electronAPI.selectDownloadDestination();if(!destination)return;const b=downloadArea==='pakistan'?PAKISTAN:(()=>{const x=m.getBounds();return{minLat:x.getSouth(),maxLat:x.getNorth(),minLng:x.getWest(),maxLng:x.getEast()};})();setDownloading(true);setProgress(null);setError('');try{const template=downloadSource==='satellite'?ONLINE_SATELLITE:downloadSource==='terrain'?ONLINE_TERRAIN.replace('{s}','a'):ONLINE_STREETS;const r=await window.electronAPI.downloadTiles({template,bounds:b,minZoom:downloadZoom,maxZoom:downloadMaxZoom,destination,maxTiles:50000});setStatus(`Downloaded ${r.downloaded.toLocaleString()} tiles • Z${downloadZoom}–Z${downloadMaxZoom}`);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setDownloading(false);}};
 const tabs:[ToolTab,string][]=[['map','Map'],['search','Search'],['coordinates','Coordinates'],['offline','Offline Data'],['download','Download']];
 return <div className="w-full h-full min-h-0 bg-slate-200 rounded-xl overflow-hidden border border-slate-300 shadow-inner relative flex flex-col">
  <div className="absolute top-3 right-3 z-[1000] flex flex-col gap-2 items-end pointer-events-none"><div className="bg-white/95 rounded-lg border shadow-lg overflow-hidden pointer-events-auto"><button title="Zoom in" onClick={()=>mapRef.current?.zoomIn()} className="block w-10 h-10 text-xl font-bold hover:bg-slate-100">+</button><button title="Zoom out" onClick={()=>mapRef.current?.zoomOut()} className="block w-10 h-10 text-xl font-bold border-t hover:bg-slate-100">−</button><button title="Reset" onClick={()=>mapRef.current?.setView([30.3753,69.3451],5)} className="block w-10 h-8 text-[10px] border-t hover:bg-slate-100">RESET</button></div><div className="bg-slate-900/90 text-white rounded-md px-3 py-1.5 text-[11px] font-mono shadow pointer-events-auto">ZOOM {zoom} / 0–19</div><div className="bg-white/95 rounded-lg border shadow-lg p-1 pointer-events-auto"><button onClick={()=>{setBaseLayer('streets');setTerrainLayer('none');}} className={`px-2 py-1.5 text-[11px] rounded ${baseLayer==='streets'?'bg-slate-800 text-white':''}`}>Streets</button><button onClick={()=>setBaseLayer('satellite')} className={`px-2 py-1.5 text-[11px] rounded ${baseLayer==='satellite'?'bg-slate-800 text-white':''}`}>Satellite</button><button onClick={()=>setTerrainLayer(v=>v==='terrain'?'none':'terrain')} className={`px-2 py-1.5 text-[11px] rounded ${terrainLayer==='terrain'?'bg-amber-600 text-white':''}`}>Terrain</button></div></div>
  <div className="absolute top-3 left-3 right-24 z-[1000] pointer-events-none"><div className="bg-white/95 rounded-xl border shadow-lg pointer-events-auto"><div className="flex items-center gap-1 p-1 border-b bg-slate-50 rounded-t-xl">{tabs.map(([id,label])=><button key={id} onClick={()=>setTool(id)} className={`px-3 py-2 text-xs font-semibold rounded-lg ${tool===id?'bg-blue-700 text-white':'text-slate-600 hover:bg-slate-200'}`}>{label}</button>)}<div className="ml-auto text-[10px] font-mono text-slate-500 px-2 hidden lg:block">{mode.toUpperCase()} • {baseLayer.toUpperCase()}{terrainLayer==='terrain'?' • TERRAIN':''}</div></div>
   {tool==='map'&&<div className="p-3 flex gap-2 items-center text-xs"><button onClick={()=>setMode('offline')} className={`px-3 py-1.5 rounded font-semibold ${mode==='offline'?'bg-green-600 text-white':'bg-slate-100'}`}>Offline</button><button onClick={()=>setMode('online')} className={`px-3 py-1.5 rounded font-semibold ${mode==='online'?'bg-blue-600 text-white':'bg-slate-100'}`}>Online</button><span className="text-slate-500">Zoom and layers stay on the map for quick access.</span></div>}
   {tool==='search'&&<div className="p-3 space-y-2"><div className="flex gap-2"><select value={searchMode} onChange={e=>setSearchMode(e.target.value as Mode)} className="border rounded px-2 text-xs"><option value="offline">Offline</option><option value="online">Online</option></select><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="City, village or place" className="flex-1 border rounded px-3 py-2 text-sm"/><button onClick={search} disabled={searching} className="bg-blue-700 text-white px-4 py-2 rounded font-semibold"><Search className="w-4 h-4 inline mr-1"/>{searching?'Searching':'Search'}</button></div>{results.slice(0,8).map((r,i)=><button key={i} onClick={()=>showResult(r)} className="block w-full text-left px-2 py-1 text-xs hover:bg-blue-50"><b>{r.name}</b> <span className="text-slate-500">{r.lat.toFixed(5)}, {r.lon.toFixed(5)}</span></button>)}</div>}
   {tool==='coordinates'&&<div className="p-3 flex flex-wrap gap-2 items-center"><Navigation className="w-4 h-4 text-blue-600"/><input value={coordinateText} onChange={e=>setCoordinateText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&goto()} className="border rounded px-3 py-2 text-sm w-64"/><button onClick={goto} className="bg-blue-700 text-white px-4 py-2 rounded font-semibold">Go to coordinate</button>{mouseCoordinate&&<span className="font-mono text-xs">Mouse: {formatCoordinate(mouseCoordinate)}</span>}</div>}
   {tool==='offline'&&<div className="p-3 space-y-3"><div className="grid md:grid-cols-3 gap-2"><button onClick={selectBase} className="flex justify-center gap-2 bg-green-600 text-white px-3 py-2 rounded font-semibold"><FolderOpen className="w-4 h-4"/>Street map folder</button><button onClick={selectSat} className="flex justify-center gap-2 bg-slate-800 text-white px-3 py-2 rounded font-semibold"><Satellite className="w-4 h-4"/>Satellite folder</button><button onClick={selectTerrain} className="flex justify-center gap-2 bg-amber-600 text-white px-3 py-2 rounded font-semibold"><Mountain className="w-4 h-4"/>Terrain folder</button></div><div className="text-[11px] font-mono text-slate-600">Streets: {scan?.tiles??0} • Satellite: {satScan?.tiles??0} • Terrain: {terrainScan?.tiles??0} <select value={scheme} onChange={e=>setScheme(e.target.value as 'xyz'|'tms')} className="ml-2 border rounded px-2 py-1"><option value="xyz">XYZ</option><option value="tms">TMS</option></select></div></div>}
   {tool==='download'&&<div className="p-3 space-y-3"><div className="flex flex-wrap gap-2 items-center"><select value={downloadSource} onChange={e=>setDownloadSource(e.target.value as 'streets'|'satellite'|'terrain')} className="border rounded px-2 py-2 text-xs"><option value="satellite">Satellite imagery</option><option value="streets">Street map</option><option value="terrain">Terrain</option></select><select value={downloadArea} onChange={e=>setDownloadArea(e.target.value as 'view'|'pakistan')} className="border rounded px-2 py-2 text-xs"><option value="view">Current view</option><option value="pakistan">Pakistan extent</option></select><label className="text-xs">Min zoom <input type="number" min="0" max="19" value={downloadZoom} onChange={e=>setDownloadZoom(Math.max(0,Math.min(19,Number(e.target.value))))} className="w-16 border rounded px-2 py-2"/></label><label className="text-xs">Max zoom <input type="number" min="0" max="19" value={downloadMaxZoom} onChange={e=>setDownloadMaxZoom(Math.max(0,Math.min(19,Number(e.target.value))))} className="w-16 border rounded px-2 py-2"/></label><button disabled={downloading} onClick={download} className="bg-indigo-600 text-white px-4 py-2 rounded font-semibold"><Download className="w-4 h-4 inline mr-1"/>{downloading?'Downloading...':'Start download'}</button></div><div className="text-[11px] text-slate-500">Zoom 0 = world. Zoom 1 = first global level. Tiles are saved as <b>zoom/x/y.png</b>. Use Offline Data to load them.</div>{progress&&<div className="text-xs font-mono">Progress {progress.done.toLocaleString()} / {progress.total.toLocaleString()} • New {progress.downloaded.toLocaleString()}</div>}</div>}
  </div></div>
  <div ref={mapEl} className="flex-1 min-h-0"/>
  <div className="absolute bottom-2 left-2 right-2 z-[1000] flex justify-between gap-2 pointer-events-none"><div className="bg-white/90 border rounded px-2 py-1 text-[10px] font-mono shadow">{status}</div>{error&&<div className="bg-red-50 text-red-700 border border-red-200 rounded px-2 py-1 text-[10px] shadow">{error}</div>}{selected&&<div className="bg-white/90 border rounded px-2 py-1 text-[10px] shadow">Selected: <b>{selected.name}</b></div>}</div>
 </div>;
}
